version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js-react"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/js-vue"
    schedule:
      interval: "daily"
